### PR TITLE
fix(RelativeRangeDatePicker): correctly close picker popup inside dialog

### LINKED ISSUE #115: RelativeRangeDatePicker: Impossible to close picker's popup when it's in a `<Dialog /> that got `disableFocusTrap={false}`.
With `disableFocusTrap=false`, it cannot be closed. With `disableFocusTrap=true` and a calendar open, it's not possible to close it while clicking outside the popups.

### PR DESCRIPTION
**Pull request by ValeraS**
Closes #115

### CODE REVIEW

File: src/components/RelativeRangeDatePicker/RelativeRangeDatePicker.tsx [hunk 1]
```diff
@@ -241,6 +241,11 @@ export function RelativeRangeDatePicker(props: RelativeRangeDatePickerProps) {
                 onClose={() => {
                     setOpen(false);
                 }}
+                focusInput={() => {
+                    setTimeout(() => {
+                        inputRef.current?.focus();
```
Comment (korvin89) [inline src/components/RelativeRangeDatePicker/RelativeRangeDatePicker.tsx:246]: Maybe add [preventScroll](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#preventscroll) option?

**Review by korvin89 — APPROVED** [review]
